// <auto-generated />
using System;
using EmitterPersonalAccount.Core.Domain.Models.Postgres;
using ExternalOrderReportService.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExternalOrderReportService.DataAccess.Migrations
{
    [DbContext(typeof(ExternalOrderReportServiceDbContext))]
    [Migration("20250421115200_add_listOSA_entity_with_metadata")]
    partial class add_listOSA_entity_with_metadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmitterPersonalAccount.Core.Domain.Models.Postgres.ListOSAReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DtMod")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Dt_Begsobr")
                        .HasColumnType("date");

                    b.Property<bool>("IsCategMeeting")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRangeMeeting")
                        .HasColumnType("boolean");

                    b.Property<int>("IssuerId")
                        .HasColumnType("integer");

                    b.Property<ListOSAMetadata>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("NomList")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ListOSAReports");
                });

            modelBuilder.Entity("EmitterPersonalAccount.Core.Domain.Models.Postgres.OrderReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExternalStorageId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IssuerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OrderReports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
